config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/users"
  get "pages/admin"
  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }
  devise_for :users, controller: {
    sessions: "users/sessions"
  }
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # # Defines the root path route ("/")
  # root "posts#index"

  resources :posts do
    post :export, on: :collection
    resources :comments
    collection do
      get :download_excel          # Normal Excel download (immediate)
      post :generate_excel         # Triggers Sidekiq job to generate Excel in the background
      # post :download_generated_excel # Downloads the Excel file generated by Sidekiq
      get :download_pdf
      get :download_image
    end
  end
  get 'download_pie_chart', to: 'posts#download_pie_chart'
  get "download_generated_excel", to: "posts#download_generated_excel", as: "download_generated_excel"

  resources :users
  root "posts#index"
  # root "pages#home"
end

app/views/loggedin/_hero.html.erb
<section class="text-black py-5">
    <div class="container mx-auto text-center">
        <h1 class="text-4xl font-bold"><%= yield :page_title %></h1>
    </div>
</section>

app/views/loggedin/_navbar.html.erb
<nav class="bg-blue-600 p-2">
    <div class="container mx-auto flex justify-between items-center">
        <%= link_to posts_path, class: "flex items-center gap-2" do %>
            <svg class="w-6 h-6 text-gray-800 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="#FFFFFF" viewBox="0 0 24 24">
                <path fill-rule="evenodd" d="M11.293 3.293a1 1 0 0 1 1.414 0l6 6 2 2a1 1 0 0 1-1.414 1.414L19 12.414V19a2 2 0 0 1-2 2h-3a1 1 0 0 1-1-1v-3h-2v3a1 1 0 0 1-1 1H7a2 2 0 0 1-2-2v-6.586l-.293.293a1 1 0 0 1-1.414-1.414l2-2 6-6Z" clip-rule="evenodd"/>
            </svg>
            <label class="text-white font-bold text-xl px-4 py-2 rounded cursor-pointer">Blog app 3.0</label>
            <%= link_to 'New Links', users_path %>
            <%#= link_to 'Blog app 3.0', posts_path, class: "text-white font-bold text-xl px-4 py-2 rounded" %>
        <% end %>
        <div class="flex items-center gap-2">
            <%= link_to " + Create New Post", new_post_path, class: "text-white font-bold text-md bg-yellow-500 hover:bg-yellow-600 px-4 py-2 rounded" %>
            <div class="flex items-center px-4 py-2 text-white">
                <%= link_to pages_home_path, class:"flex items-center" do %>
                    <svg class="w-6 h-6 dark:text-white" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="currentColor" viewBox="0 0 24 24">
                        <path fill-rule="evenodd" d="M12 4a4 4 0 1 0 0 8 4 4 0 0 0 0-8Zm-2 9a4 4 0 0 0-4 4v1a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2v-1a4 4 0 0 0-4-4h-4Z" clip-rule="evenodd"/>
                    </svg>
                    <% if current_user %>
                        <label class="font-semibold cursor-pointer"><%= current_user.email.split('@').first.capitalize %></label>
                    <% else %>
                        <%= link_to "Login", new_user_session_path, class: "text-white font-semibold" %>
                    <% end %>
                <% end %>
            </div>
        </div>
    </div>
</nav>