config/routes.rb
Rails.application.routes.draw do
  get "pages/home"
  get "pages/users"
  get "pages/admin"
  devise_for :admins, controllers: {
    sessions: "admin/sessions",
    registrations: "admin/registrations"
  }
  devise_for :users, controller: {
    sessions: "users/sessions"
  }
  # # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # # Can be used by load balancers and uptime monitors to verify that the app is live.
  # get "up" => "rails/health#show", as: :rails_health_check

  # # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # # Defines the root path route ("/")
  # root "posts#index"

  resources :posts do
    post :export, on: :collection
    resources :comments
    collection do
      get :download_excel          # Normal Excel download (immediate)
      post :generate_excel         # Triggers Sidekiq job to generate Excel in the background
      # post :download_generated_excel # Downloads the Excel file generated by Sidekiq
      get :download_pdf
      get :download_image
    end
  end
  get 'download_pie_chart', to: 'posts#download_pie_chart'
  get "download_generated_excel", to: "posts#download_generated_excel", as: "download_generated_excel"

  resources :users
  root "posts#index"
  # root "pages#home"
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :comments
  has_many_attached :images
  has_rich_text :body

  validates :title,  presence: true
  validates :content, presence: true
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, except: [:show, :index]

  def index
    @posts = Post.where(is_removed: false).order(created_at: :desc)
  end

  def new
    @post = Post.new
    respond_to do |format|
      format.html {render "posts/new" }
    end
  end


  def create
    @post = Post.new(post_params)
    @post.user = current_user
    if @post.save
      Rails.logger.info("if save me aaya")
      respond_to do |format|
        Rails.logger.info("format turbo next")
        format.html { redirect_to posts_path, notice: "Congrats! The internet has been blessed with your wisdom. " }
        Rails.logger.info("congrats")
      end
    else
      Rails.logger.info("else me aaya")
      render :new
    end
  end


  def show
    @post = Post.find(params[:id])

    unless @post && !@post.is_removed
      redirect_to posts_path, alert: "Oops! This post doesn't exist or has been removed."
    end
  end


  def update
    @post = Post.find(params[:id])

    if @post.update(post_params)
      redirect_to @post, notice: "Post was successfully updated."
    else
      render :edit
    end
  end


  def edit
    @post = Post.find(params[:id])
  end

  def destroy
    @post = Post.find(params[:id])
    if @post.user_id == current_user.id
      if @post.update(is_removed: true)
        redirect_to posts_path, notice: "Poof! Your post just vanished into the void. 🎩✨"
      else
        redirect_to @post, alert: "Oops! Even the internet refused to delete this post."
      end
    else
      redirect_to @post, alert: "Noo my friend... If you didn’t write it, you can’t wipe it!"
    end
  end

  def download_excel
    Rails.logger.info("download_excel me aaya")
    posts = Post.all
    service = DownloadPostsService.new(posts)
    package = service.generate_xlsx

    send_data package.to_stream.read,
              filename: "posts_sidekiq_#{Time.now.to_i}.xlsx",
              type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end

  def download_pie_chart
    posts = Post.all
    service = DownloadPostsService.new(posts)
    package = service.generate_pie_chart_xlsx
  
    send_data package.to_stream.read,
              filename: "posts_pie_chart_#{Time.now.to_i}.xlsx",
              type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  end
  

  def export
    file_name = "posts_sidekiq_#{Time.now.to_i}.xlsx"
    
    # Ensure job is enqueued properly
    GenerateExcelJob.perform_later(file_name)

    # Return JSON response with file path
    render json: { download_url: "/exports/#{file_name}" }, status: :accepted
  rescue => e
    Rails.logger.error "Export error: #{e.message}"
    render json: { error: "Failed to process export" }, status: :internal_server_error
  end

  # def download_generated_excel
  #   Rails.logger.info("download_generated_excel me aaya")

  #   file_data = Rails.cache.read("posts_xlsx")

  #   if file_data
  #     Rails.logger.info("download_generated_excel: file found")
  #     send_data file_data,
  #               filename: "posts.xlsx",
  #               type: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"
  #   else
  #     Rails.logger.info("download_generated_excel: file not ready yet")
  #     flash[:alert] = "File is not ready yet. Please try again later."
  #     redirect_to posts_path
  #   end
  # end

  def download_pdf
    @posts = Post.all
    respond_to do |format|
      format.html
      format.pdf do
        render pdf: "posts_#{Time.now.to_i}", template: "posts/download_pdf", formats: [:html]
      end
    end
  end

  def download_image
    @posts = Post.all
    html = render_to_string("posts/index", layout: false)
  
    # Generate image using IMGKit
    kit = IMGKit.new(html, quality: 80)
  
    send_data kit.to_img(:png),
              filename: "posts_image_#{Time.now.to_i}.png",
              type: "image/png",
              disposition: "attachment"
  end

  private

  def post_params
    params.require(:post).permit(:title, :content, :is_removed, :body, images: [])
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<div class="container mx-auto p-4 shadow-md rounded-lg">
  <%= simple_form_for @post do |f| %>
    <div class="mb-3">
      <label class="font-bold">Title:</label>
      <%= f.text_field :title, class: 'w-full bg-white px-2 py-1 border rounded focus:outline-none focus:ring-2', required: true %>
    </div>
    <div class="mb-3">
    <label class="font-bold">Content:</label>
      <%= f.text_area :content, class: 'w-full bg-white px-2 py-1 border rounded focus:outline-none focus:ring-2', required: true %>

    </div>
    <% if @post.images.attached? %>
  <div class="mt-4 mb-4 grid grid-cols-2 md:grid-cols-3 gap-4">
    <% @post.images.each do |image| %>
      <div class="bg-gray-200 rounded-lg rounded-lg p-2 ">
        <%= image_tag image, class: "w-full h-auto rounded" %>
        <%#= button_to 'Delete', delete_image_post_path(@post, image.signed_id), method: :delete, class: "bg-red-500 text-white px-2 py-1 rounded hover:bg-red-700" %>
      </div>
    <% end %>
  </div>
<% end %>
    <div class="flex items-center gap-5">
      <h5>Change in thoughts? Sure.</h5>
      <%= f.button :submit, 'Update post', class: "bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-700" %>
    </div>
  <% end %>
</div>

app/views/posts/_posts.html.erb
<% @posts.each do |post| %>
    <div class="post-item flex items-center shadow-md rounded-lg p-2 mb-2 gap-5 bg-yellow-50">
        <div class="p-2">
            <div class="flex items-end gap-5 py-2 ">
            <%= link_to post, class: "text-xl text-blue-500 underline font-bold ", data: { turbo: false } do %>
            <label id="post_<%= post.id %>_title" class="cursor-pointer">
                <%= post.title %>
            </label>
            <% end %>

            
            <label class="text-sm text-blue-500">
                by <%= link_to post.user.email.split('@').first.capitalize if post.user.present? %>
                <%#= link_to post.user.email.split('@').first.capitalize, user_path(post.user), class: "underline hover:text-blue-700" if post.user.present? %>

            </label>
            </div>
            <p id="post_<%= post.id %>_content" class="px-2 text-base">
            <% if post.content.split.size > 50 %>
                <%= post.content.split[0..50].join(" ") %>...
                <%= link_to "Read More", post, class: "text-blue-500 underline" %>
            <% else %>
                <%= post.content %>
            <% end %>
            </p>
        </div>
        <div class="flex items-center text-sm px-2 py-1 rounded-full gap-1">
            <%= link_to post_path(post), class: "cursor-pointer" do %>
            <svg width="25" height="25" viewBox="0 0 24 24" fill="none" xmlns="http://www.w3.org/2000/svg" transform="rotate(0 0 0)">
                <path fill-rule="evenodd" clip-rule="evenodd" d="M2.50002 12.0957C2.50002 6.849 6.75332 2.5957 12 2.5957C17.2467 2.5957 21.5 6.849 21.5 12.0957C21.5 17.3424 17.2467 21.5957 12 21.5957H3.25002C2.94668 21.5957 2.6732 21.413 2.55711 21.1327C2.44103 20.8525 2.50519 20.5299 2.71969 20.3154L4.77303 18.262C3.35633 16.603 2.50002 14.4488 2.50002 12.0957ZM12 4.0957C7.58174 4.0957 4.00002 7.67742 4.00002 12.0957C4.00002 14.305 4.89463 16.304 6.34317 17.7526C6.48382 17.8932 6.56284 18.084 6.56284 18.2829C6.56284 18.4818 6.48382 18.6726 6.34317 18.8132L5.06068 20.0957H12C16.4183 20.0957 20 16.514 20 12.0957C20 7.67742 16.4183 4.0957 12 4.0957Z" fill="#343C54"/>
            </svg>
            <% end %>
            <%= post.comments.where(is_deleted: false).count %>
        </div>
    </div>
<% end %>

app/views/posts/download_pdf.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>Posts PDF</title>
  <style>
    body { font-family: Arial, sans-serif; }
    table { width: 100%; border-collapse: collapse; }
    th, td { border: 1px solid black; padding: 8px; text-align: left; }
    th { background-color: #f2f2f2; }
  </style>
</head>
<body>
  <h1>Posts List</h1>
  <table>
    <thead>
      <tr>
        <th>#</th>
        <th>Title</th>
        <th>Content Length</th>
        <th>Comments Count</th>
        <th>Created By</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each_with_index do |post, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= post.title %></td>
          <td><%= post.content.length %></td>
          <td><%= post.comments.count %></td>
          <td><%= post.user&.email.presence || "N/A" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</body>
</html>

app/views/posts/edit.html.erb
<%= turbo_frame_tag "turbo-content" do %>
    <% content_for :page_title, "Editing #{@post.title}" %>
    <div class="bg-yellow-50">
        <%= render 'form' %>
    </div>
<% end %>

app/views/posts/index.html.erb
<%= turbo_frame_tag "turbo-content" do %>
  <div data-controller="posts">
    <% content_for :page_title, "Welcome to Blog App" %>
   
    <div class="container mx-auto py-2">
      <div class="flex gap-5 mb-4 p-2 bg-gray-200">
        <input type="text" id="searchInput" placeholder="Search posts..." class="w-1/3 bg-white placeholder:text-slate-400 text-slate-700 text-sm border border-slate-200 rounded-md pl-3 pr-28 px-3 py-2 transition duration-300 ease focus:outline-none focus:border-slate-400 hover:border-slate-300 shadow-sm focus:shadow">
        <p id="searchResultsPosts" class="whitespace-nowrap mt-2"></p>
      </div>
      
      <div id="post_container" class="p-2">
        <%= render partial: "posts/posts", locals: { posts: @posts } %>
      </div>
      <div class="flex justify-center gap-2 items-center mt-4">
        <button id="post_prev_page" class="flex items-center px-2 py-1 bg-gray-300 rounded">
          <svg class="w-3.5 h-3.5 me-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M13 5H1m0 0 4 4M1 5l4-4"/>
          </svg>
          Previous
        </button>
        <div id="post_page_numbers" class="flex gap-2"></div>
        <button id="post_next_page" class="flex items-center px-2 py-1 bg-gray-300 rounded">
          Next
          <svg class="w-3.5 h-3.5 ms-2 rtl:rotate-180" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 14 10">
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M1 5h12m0 0L9 1m4 4L9 9"/>
          </svg>
        </button>
      </div>
      <p id="post_page_info" class="text-center mt-2"></p>
    </div>
  </div>

  <div class="p-5">
    <div class="flex justify-between mb-2">
      <%#= link_to "Download as Excel", download_excel_posts_path(format: :xlsx), class: "bg-green-500 text-white px-4 py-2 rounded hover:bg-green-700" %>
      <!-- download buttonto generate excel file using service file -->
      <div class="flex items-center p-2 gap-5">
        <%= link_to download_excel_posts_path(format: :xlsx), class: "text-green-500 rounded hover:text-green-700 flex items-center" do %>
          <svg class="w-8 h-8 text-green-500 hover:text-green-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M13 11.15V4a1 1 0 1 0-2 0v7.15L8.78 8.374a1 1 0 1 0-1.56 1.25l4 5a1 1 0 0 0 1.56 0l4-5a1 1 0 1 0-1.56-1.25L13 11.15Z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M9.657 15.874 7.358 13H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2h-2.358l-2.3 2.874a3 3 0 0 1-4.685 0ZM17 16a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17Z" clip-rule="evenodd"/>
          </svg>
        <% end %>
        <!-- Blue Button - Axlsx with Pie Chart -->
        <%= link_to download_pie_chart_path(format: :xlsx), class: "text-blue-500 rounded hover:text-blue-700 flex items-center gap-2" do %>
          <svg class="w-8 h-8 text-blue-500 hover:text-blue-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" fill="none"/>
            <path d="M12 2 A10 10 0 0 1 22 12 L12 12 Z" fill="currentColor"/>
          </svg>
        <% end %>

        <!-- download button to generate excel file using sidekiq -->
        <%= link_to "#", id: "download_posts_sidekiq", class: "text-yellow-300 rounded hover:text-yellow-700 flex items-center" do %>
          <svg class="w-8 h-8 text-yellow-300 hover:text-yellow-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M13 11.15V4a1 1 0 1 0-2 0v7.15L8.78 8.374a1 1 0 1 0-1.56 1.25l4 5a1 1 0 0 0 1.56 0l4-5a1 1 0 1 0-1.56-1.25L13 11.15Z" clip-rule="evenodd"/>
            <path fill-rule="evenodd" d="M9.657 15.874 7.358 13H5a2 2 0 0 0-2 2v4a2 2 0 0 0 2 2h14a2 2 0 0 0 2-2v-4a2 2 0 0 0-2-2h-2.358l-2.3 2.874a3 3 0 0 1-4.685 0ZM17 16a1 1 0 1 0 0 2h.01a1 1 0 1 0 0-2H17Z" clip-rule="evenodd"/>
          </svg>
        <% end %>

        <!-- Yellow Button - Download Picture using js canvas  -->
        <%= button_tag type: "button", id: "download_posts_image", class: "text-yellow-500 rounded hover:text-yellow-700 flex items-center gap-2" do %>
          <svg class="w-8 h-8 text-yellow-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
            <path fill="currentColor" d="M16 18H8l2.5-6 2 4 1.5-2 2 4Zm-1-8.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"/>
            <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 3v4a1 1 0 0 1-1 1H5m14-4v16a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V7.914a1 1 0 0 1 .293-.707l3.914-3.914A1 1 0 0 1 9.914 3H18a1 1 0 0 1 1 1ZM8 18h8l-2-4-1.5 2-2-4L8 18Zm7-8.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"/>
          </svg>
        <% end %>

        <!-- Red Button - PDF Download using wickedpdf -->
        <%= link_to download_pdf_posts_path(format: :pdf), class: "text-red-500 rounded hover:text-red-700 flex items-center gap-2" do %>
          <svg class="w-8 h-8 text-red-500 hover:text-red-700" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
            <path fill-rule="evenodd" d="M9 2.221V7H4.221a2 2 0 0 1 .365-.5L8.5 2.586A2 2 0 0 1 9 2.22ZM11 2v5a2 2 0 0 1-2 2H4a2 2 0 0 0-2 2v7a2 2 0 0 0 2 2 2 2 0 0 0 2 2h12a2 2 0 0 0 2-2 2 2 0 0 0 2-2v-7a2 2 0 0 0-2-2V4a2 2 0 0 0-2-2h-7Zm-6 9a1 1 0 0 0-1 1v5a1 1 0 1 0 2 0v-1h.5a2.5 2.5 0 0 0 0-5H5Zm1.5 3H6v-1h.5a.5.5 0 0 1 0 1Zm4.5-3a1 1 0 0 0-1 1v5a1 1 0 0 0 1 1h1.376A2.626 2.626 0 0 0 15 15.375v-1.75A2.626 2.626 0 0 0 12.375 11H11Zm1 5v-3h.375a.626.626 0 0 1 .625.626v1.748a.625.625 0 0 1-.626.626H12Zm5-5a1 1 0 0 0-1 1v5a1 1 0 1 0 2 0v-1h1a1 1 0 1 0 0-2h-1v-1h1a1 1 0 1 0 0-2h-2Z" clip-rule="evenodd"/>
          </svg>
        <% end %>
      </div>

      <%= link_to download_image_posts_path, class: "text-red-500 px-4 py-2 rounded hover:text-red-700 flex items-center gap-2" do %>
        <svg class="w-8 h-8 text-red-500" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="none" viewBox="0 0 24 24">
          <path fill="currentColor" d="M16 18H8l2.5-6 2 4 1.5-2 2 4Zm-1-8.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"/>
          <path stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M10 3v4a1 1 0 0 1-1 1H5m14-4v16a1 1 0 0 1-1 1H6a1 1 0 0 1-1-1V7.914a1 1 0 0 1 .293-.707l3.914-3.914A1 1 0 0 1 9.914 3H18a1 1 0 0 1 1 1ZM8 18h8l-2-4-1.5 2-2-4L8 18Zm7-8.5a.5.5 0 1 1-1 0 .5.5 0 0 1 1 0Z"/>
        </svg>
      <% end %>

      <!-- Filter Toggle Button -->
      <button id="toggleFilter" class="p-2 bg-gray-200 rounded hover:bg-gray-300">
        <svg class="w-6 h-6 text-gray-800" aria-hidden="true" xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" viewBox="0 0 24 24">
          <path d="M5.05 3C3.291 3 2.352 5.024 3.51 6.317l5.422 6.059v4.874c0 .472.227.917.613 1.2l3.069 2.25c1.01.742 2.454.036 2.454-1.2v-7.124l5.422-6.059C21.647 5.024 20.708 3 18.95 3H5.05Z"/>
        </svg>
      </button>
    </div>
<div id="filterSection" class="mb-4 grid grid-cols-4 gap-4 hidden">
  <!-- 1st Row: Search & Content Length Inputs -->
  <input type="text" id="search_title" placeholder="Search by Title" class="border p-2 rounded text-center">
  <input type="text" id="search_created_by" placeholder="Search by Created By" class="border p-2 rounded text-center">
  <input type="number" id="min_content_length" placeholder="Min Content Length" class="border p-2 rounded text-center">
  <input type="number" id="max_content_length" placeholder="Max Content Length" class="border p-2 rounded text-center">
  <div class="col-span-3 w-1/2 justify-center items-end">
    <label class="block mb-2 text-sm font-medium text-gray-900">Content Length Range</label>
    <div class="relative w-full flex items-center space-x-2">
      <!-- Min Range Slider -->
      <input id="min-range" type="range" min="0" max="500" value="0"
        class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700">
      <!-- Max Range Slider -->
      <input id="max-range" type="range" min="0" max="500" value="500"
        class="w-full h-2 bg-gray-200 rounded-lg appearance-none cursor-pointer dark:bg-gray-700">
    </div>
    <div class="flex justify-between text-sm text-gray-700 mt-2">
      <span>Min: <span id="min-value">0</span></span>
      <span>Max: <span id="max-value">500</span></span>
    </div>
  </div>
  <div class="col-span-1 flex justify-center items-center">
    <button id="apply_filters" class="bg-blue-500 text-white px-4 py-2 rounded hover:bg-blue-700">
      Apply Filters
    </button>
  </div>
</div>



    <table id="posts_table" class="min-w-full border border-gray-300 bg-white shadow-lg">
      <thead>
        <tr class="bg-gray-200">
          <th class="px-4 py-2 border">#</th>
          <th class="px-4 py-2 border">Title</th>
          <th class="px-4 py-2 border">Content Length</th>
          <th class="px-4 py-2 border">Comments Count</th>
          <th class="px-4 py-2 border">Created By</th>
          <th class="px-4 py-2 border">Actions</th>
        </tr>
      </thead>
      <tbody id="posts_table_body">
        <% @posts.each_with_index do |post, index| %>
          <tr class="post_row text-center">
            <td class="px-4 py-2 border index-column"><%= index + 1 %></td>
            <td class="px-4 py-2 border post-title">
              <%= link_to post_path(post), data: { turbo_frame: "post_details", turbo_action: "advance" }, class: 'block w-full py-2' do %>
                <%= post.title %>
              <% end %>
            </td>
            <td class="px-4 py-2 border post-content-length"><%= post.content.length %></td>
            <td class="px-4 py-2 border"><%= post.comments.count %></td>
            <td class="px-4 py-2 border post-created-by"><%= post.user&.email.presence || "N/A" %></td>
            <td class="px-4 py-2 border"> 
              <%= link_to 'View', post_path(post), class: "bg-blue-500 text-white px-3 py-1 rounded hover:bg-blue-700" %>
              <% if post.user == current_user %>
                <%= link_to 'Edit', edit_post_path(post), class: "bg-yellow-500 text-white px-3 py-1 rounded hover:bg-yellow-700" %>
                <%= link_to 'Delete', post_path(post), method: :delete, data: { confirm: 'Are you sure?' }, class: "bg-red-500 text-white px-3 py-1 rounded hover:bg-red-700" %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>

    </table>
    <!-- Pagination Controls -->
    <div class="flex justify-between items-center mt-4">
      <button id="prev_page" class="bg-gray-500 text-white px-4 py-2 rounded invisible">Previous</button>
      <span id="page_info" class="text-gray-700"></span>
      <button id="next_page" class="bg-gray-500 text-white px-4 py-2 rounded">Next</button>
    </div>
    <div id="page_numbers" class="flex justify-center mt-2"></div>
  </div>
  <div id="posts_container_image" class=" p-4 bg-white border rounded shadow">
  <h2 class="text-lg font-bold mb-4">Posts</h2>
  <table class="w-full border-collapse border border-gray-300">
    <thead>
      <tr class="bg-gray-200">
        <th class="border p-2">ID</th>
        <th class="border p-2">Title</th>
        <th class="border p-2">Content Length</th>
        <th class="border p-2">Comments Count</th>
        <th class="border p-2">Created By</th>
      </tr>
    </thead>
    <tbody>
      <% @posts.each do |post| %>
        <tr>
          <td class="border p-2"><%= post.id %></td>
          <td class="border p-2"><%= post.title %></td>
          <td class="border p-2"><%= post.content.length %></td>
          <td class="border p-2"><%= post.comments.count %></td>
          <td class="border p-2"><%= post.user&.email || "N/A" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>
<% end %>
<script src="https://cdnjs.cloudflare.com/ajax/libs/html2canvas/1.4.1/html2canvas.min.js"></script>
<script>
  document.addEventListener('turbo:load', function () {
  const toggleButton = document.getElementById("toggleFilter");
  const filterSection = document.getElementById("filterSection");

  toggleButton.addEventListener("click", function () {
    filterSection.classList.toggle("hidden");
  });
});

// sidekiq - button click to start POST
document.getElementById("download_posts_sidekiq").addEventListener("click", function(event) {
  event.preventDefault();
  
  fetch("<%= export_posts_path %>", { method: "POST", headers: { "X-CSRF-Token": "<%= form_authenticity_token %>" } })
    .then(response => response.json())
    .then(data => {
      if (data.download_url) {
        setTimeout(() => { 
          window.location.href = data.download_url; 
        }, 2000); // Wait 2 seconds for Sidekiq to finish
      }
    });
  });

  // script to generate image using canvas in js
  document.getElementById("download_posts_image").addEventListener("click", function () {
    let postsContainer = document.getElementById("posts_container_image");

    html2canvas(postsContainer, { scale: 2 }).then(canvas => {
      let link = document.createElement("a");
      let timestamp = Math.floor(Date.now() / 1000);
      link.href = canvas.toDataURL("image/png");
      link.download = `posts_image_${timestamp}.png`;
      link.click();
    });
  });
</script>